<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"chuqin"
                    }
                ],
                "menu":"考勤管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"知识库管理",
                        "menuJump":"列表",
                        "tableName":"zhishiku"
                    }
                ],
                "menu":"知识库管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"部门管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_bumen"
                    }
                ],
                "menu":"部门管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职位管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_zhiwei"
                    }
                ],
                "menu":"职位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"知识类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_zhishi"
                    }
                ],
                "menu":"知识类型管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"chuqin"
                    }
                ],
                "menu":"考勤管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"知识库管理",
                        "menuJump":"列表",
                        "tableName":"zhishiku"
                    }
                ],
                "menu":"知识库管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
